services:
  - type: web
    name: ams-incident-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8001
    envVars:
      - key: APPLICATION_NAME
        value: AMS Incident Agent
      - key: APPLICATION_VERSION
        value: 1.0.0
      - key: ENVIRONMENT
        value: PROD
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
